[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer_runs = 800
via_ir = true
ffi = true

[dependencies]
forge-std = "^1.0.0"
openzeppelin-contracts = "^5.0.2"
"@pythnetwork/pyth-sdk-solidity" = "2.2.0"

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
